server:
  port: 8080
spring:
  profiles:
    active: local
logging:
  config: classpath:logback-${spring.profiles.active}.xml
---
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/chmap2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug
  messages:
    basename: messages
